import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const kudry = localFont({
	src: '../public/kudry_weird-headline.otf',
	display: 'swap',
	variable: '--font-kudry',
});
const kurale = Montserrat({
	weight: ['500', '600'],
	display: 'swap',
	variable: '--font-kurle',
	subsets: ['cyrillic'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body className={`${kurale.variable} ${kudry.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
